### ISSUE TITLE
[V2] No Animation When Minimizing, Maximizing and Restoring and Some Bugs on Frameless Window

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#1084]
**Description**
You know when minimizing or maximizing the animation appear on Windows (Not sure if this works on OSX) as the window moves to the task bar. However if the window set to frameless, then the animation does not happen and the window just disappear in a flash.

**To Reproduce**
1. Set ``Frameless: true`` in ``&options.App``.
2. Use the runtime method ``window.runtime.WindowMinimise()`` in Javascript on a button.

**Expected behaviour**
Animation should starts as normal.

**System Details**
```cmd
System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       97.0.1072.62
npm             N/A             Installed       6.14.13
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
```

**Comment by stffabi** [comment]
I've created a draft PR #1085 which should fix this issue and it also contains several improvements for frameless window on windows. Would it be possible for you @KiddoV to give it a try? I currently only have a Windows 11 machine to develop the code.

**Comment by KiddoV** [comment]
@stffabi thanks! I will try that. Also, is there a way to toggle WindowMaximize instead? I just want the main window go back to normal after clicking the maximize button again.

**Comment by KiddoV** [comment]
@stffabi I tried your PR and it works!!!
Thank you so much!!!
##########
One more issue with the frameless window though, that is the padding of the window is not correct, see image:
- This image shows the ``resize cursor`` appear not at the right position (The red line is where the cursor appear which is wrong, should be by the edge of the window!!!)
![Capture2 PNG 2022_01_18_12_00_19 0](https://user-images.githubusercontent.com/28552977/149993023-3053f149-7453-4051-9eba-6531b61f1266.png)

- Also when maximize, any elements that close to the edge got cut-out:
![Capture1](https://user-images.githubusercontent.com/28552977/149991659-63c88744-d5cb-4cc9-b601-edc0ef9fecc1.PNG)

**Comment by stffabi** [comment]
@KiddoV Awesome thanks for testing.

Regarding the two issues, I have some changes in the pipeline to fix the cut-out bug. This is a new one introduced with the Draft-PR.

The other one needs some more investigation, but I have an idea where to look.

**Comment by KiddoV** [comment]
@stffabi you are amazing. Be waiting for your PR.

**Comment by leaanthony** [comment]
Awesome testing @KiddoV ! Thanks 🙏

**Comment by stffabi** [comment]
@KiddoV I've pushed a fix for the cut-off onto the Draft-PR

**Comment by KiddoV** [comment]
@stffabi I tested it. Not sure why ``scaledWidth := (width * int(dpix)) / 96`` and ``scaledHeight := (height * int(dpiy)) / 96`` didn't work for me. It works when I set ``Fullscreen: true,``.
So, I change it to:
```go
...
	scaledWidth := (width * int(dpix)) / 45
	scaledHeight := (height * int(dpiy)) / 45
...
```
...works perfectly on Windows 10 at res 1920x1080. Unfortunately, not working on Windows 7, as soon as I click the button with ``window.runtime.WindowMaximise()`` it will crash (or close) the app immediately.

**Comment by stffabi** [comment]
What do you mean by didn't work? What was the result? Scaling with 45 makes no sense to me, everything is 96dpi with default 100% scaling.

Window7: Did it crash yesterday? What's the output when run with `--debug`?

**Comment by stffabi** [comment]
Regarding Windows7: Please update to the lastest version of the PR, that should fix the crash on Windows 7.

**Comment by KiddoV** [comment]
> What do you mean by didn't work? What was the result? Scaling with 45 makes no sense to me, everything is 96dpi with default 100% scaling.
> 
> ~Window7: Did it crash yesterday? What's the output when run with `--debug`?~

IDK. When using 96dpi I still have a little bit of cut-off:
![Capture](https://user-images.githubusercontent.com/28552977/150135051-1e6ab91a-3f99-40f9-a3f4-76ff21018e0f.PNG)
Using 45dpi looks good to me:
![Capture](https://user-images.githubusercontent.com/28552977/150135245-3719107a-7ed2-4ef8-9467-6d62873afcd2.PNG)

**Comment by KiddoV** [comment]
> Regarding Windows7: Please update to the lastest version of the PR, that should fix the crash on Windows 7.

Works on Windows 7 now, Thank you!

**Comment by stffabi** [comment]
@KiddoV thanks for the hint to the `Fullscreen: true` mode, that helped me to get the right fix. I've updated the PR again and it should now fix the cut-off on Windows 7, 10 and 11.
Could you please give it another try, that would be awesome?

**Comment by KiddoV** [comment]
@stffabi I tested. It works flawlessly on Windows 10 and 7. Thank you so much!
I still have 2 issues in mind:
- Are you going to work on the ``resize`` thing? I don't think we need the menu support for frameless window. That can be handle in the front-end.
- Can you implement the toggle for ``window maximize``, so we can click the maximize button again (when the window at the maximize state) to get the window back to the default size. Maybe add a ``WindowToggleMaximise`` method the the ``runtime``. I wish I can be more helpful, I only started to learn Go a few days ago.

**Comment by stffabi** [comment]
@KiddoV thanks so much for your great testing on both platforms 🙏 

Unfortunately I currently have not enough spare time to resolve those two issues as mentioned in the PR. 

AFAIK @leaanthony will take a look into the `resizing` problem with a future PR, maybe you could open a new issue just for that problem?
Regarding the `toggle min/max` it would be also great to open another issue for that. So we could track both problems independently and we could close this issue as soon as #1085 has been merged.

**Comment by KiddoV** [comment]
@stffabi thanks for the suggestion. I appreciate your work!

**Comment by leaanthony** [comment]
> I wish I can be more helpful, I only started to learn Go a few days ago. 

Seriously, I cannot tell you just how helpful thorough testing and solid feedback is. It saves everyone so much time (look how @stffabi was able to quickly hone in on the bugs based on your testing) and everyone wins. You're providing an amazing contribution. Thanks! 🙏
