### ISSUE TITLE
Error: no index.html found

### ISSUE THREAD

**Issue by diorodrigu** [wailsapp/wails#1971]
### Description

If you create a new project using init it works normally. But right after I upload your project to github and clone to another location, this problem simply occurs.
.gitignore has not been changed, it is by default

### To Reproduce

wails dev

### Expected behaviour

run app

### Screenshots

![image](https://user-images.githubusercontent.com/37380674/195699096-30f650f6-6220-409d-aa5f-d5ee29c97bb6.png)

### Attempted Fixes

I checked that the files were in frontend and I also tried to replace with the default

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Manjaro Linux
Version: 	Unknown
ID:		manjaro
Go Version:	go1.19
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0
Package Manager: 	pacman

Dependency	Package Name	Status		Version
----------	------------	------		-------
*docker 	docker 		Installed 	1:20.10.17-1
gcc 		gcc 		Installed 	12.2.0-1
libgtk-3 	gtk3 		Installed 	1:3.24.34-1
libwebkit 	webkit2gtk 	Installed 	2.36.7-1
npm 		npm 		Installed 	8.19.1-1
pkg-config 	pkgconf 	Installed 	1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

I was also unable to reproduce it, but according to the error message PR #1972 should fix this. @dxdns would it be possible for you to test the PR?

Please see this [guide](https://wails.io/docs/next/guides/bleeding-edge#testing-a-pr) for testing a PR.

**Comment by leaanthony** [comment]
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Comment by taylorlanglopez** [comment]
I still have this issue. 

Description
If you move your project up to github then to a different machine, wails dev fails to build the application (on the original machine) and launch it due to an error stating "Error: no index.html foundwatching:C:\Projects\<project-name>\frontend"

To Reproduce
- Run project normally on first machine (Windows Machine)
- Go home, clone that same repo, run it just fine (Linux)
- Go back first machine, pull your changes, run wails dev and it will error out (Windows Machine)

Expected behaviour
The app launches correctly. 

Screenshots
![image](https://user-images.githubusercontent.com/17031890/214926329-46244565-af63-4f2b-8615-7c3496a9b176.png)


Attempted Fixes
I checked that the files were in frontend. I replaced it with default, I tried to make a default template wails program per the docs  and follow the same steps to see if it really was my fault. 

This error occurs if I make a template project, simply upload to github and then clone it to a different machine. It will work on the second machine, but if I pull that same repo after a single line change (not in index.html, just adding a comment to main.go) it will fail to see index.html on the first machine.

First PC (Works) -> Second PC (Works) -> Back to First PC (Doesn't work)

System Details
Wails CLI v2.0.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.19.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       109.0.1518.61
npm             N/A             Installed       8.19.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download

Additional context
I've only used the command wails dev in this troubleshooting effort, wails build also fails with the same index.html error. I've only been trying to use wails dev so that I can have the file watching reload feature during development.

**Comment by stffabi** [comment]
Have you tried to update to the latest Wails version? There have been several improvements since 2.0.0 release.

**Comment by taylorlanglopez** [comment]
This happens regardless of wails version. My boxes at home are on wails latest as of yesterday.

**Comment by stffabi** [comment]
Maybe you can point to a demo repo on github where this occurs?

**Comment by taylorlanglopez** [comment]
I can try to put one up later. I updated to the latest version and got a different looking error?

![image](https://user-images.githubusercontent.com/17031890/214932467-20f8420f-19c9-4a2a-8437-0ab4b991ed8c.png)

Maybe that will help.

**Comment by taylorlanglopez** [comment]
![image](https://user-images.githubusercontent.com/17031890/214966923-be4b7d78-3f5b-4641-a5a2-2e64de5d2946.png)

This is wails build on the same repo
