### ISSUE TITLE
Error: 'default' is not exported by react/jsx-runtime, imported by node_modules/@preact/signals-react/dist/signals.module.js

### ISSUE THREAD

**Issue by learncodingforweb** [wailsapp/wails#1993]
### Description

calling preact signal for state management causes error in react-ts app

### To Reproduce

1. wails init -n myproject -t react-ts
2. cd frontend && yarn add  @preact/signals-react
3. using following code in App.tsx
`
    import { signal } from '@preact/signals-react';
    import { useEffect, useState } from 'react';

    function App() {
      const counter = signal(0)
      const [state, setState] = useState(0);
      useEffect(() => {
        counter.subscribe(v => {
            setState(v);
        })
      }, [counter])
     return (
        <>
            <p>Preact signal</p>
            <p>Count {state }</p>
            <button onClick={() => counter.value=counter.value+1}>Inc</button>
        </>
      )
  }
  export default App
`
4. It give following error
    **Error: 'default' is not exported by react/jsx-runtime, imported by node_modules/@preact/signals-react/dist/signals.module.js**

**Note, if i go to cd frontend and yarn dev, on browser open the http://localhost:5173. it is not giving any error**

### Expected behaviour

it should work on running wails dev

### System Details

```shell
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by leaanthony** [comment]
Hi. Is this a Wails bug?

**Comment by learncodingforweb** [comment]
seems like as if running running front alone it is working fine.
test using
cd frontend && yarn dev and open in browser link

**Comment by leaanthony** [comment]
Yeah but that might not be a Wails bug. It might be that signals doesn't work with webviews.

**Comment by learncodingforweb** [comment]
How can we resolve this issue?

**Comment by gregorip02** [comment]
I don't think it's a wails bug, it happened to me with a Laravel, React and Vite application. 
I fixed it putting `jsxRuntime: classic` in react plugin at `vite.config.js`
```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    /* More plugin settings */
    react({
      jsxRuntime: 'classic'
    })
  ]
})

```

**Comment by learncodingforweb** [comment]
**Still getting following error**

`[vite] Internal server error: Transform failed with 4 errors:
C:/dev/learn/myproject/frontend/src/main.tsx:8:30: ERROR: Duplicate "__self" prop found:
C:/dev/learn/myproject/frontend/src/main.tsx:8:44: ERROR: Duplicate "__source" prop found:
C:/dev/learn/myproject/frontend/src/main.tsx:13:13: ERROR: Duplicate "__self" prop found:
C:/dev/learn/myproject/frontend/src/main.tsx:13:27: ERROR: Duplicate "__source" prop found:
  Plugin: vite:esbuild
  File: C:/dev/learn/myproject/frontend/src/main.tsx:11:21
  
  Duplicate "__self" prop found:
  6  |  const container = document.getElementById('root');
  7  |  const root = createRoot(container!);
  8  |  root.render(<React.StrictMode __self={this} __source={{
     |                                ^
  9  |    fileName: _jsxFileName,
  10 |    lineNumber: 11,

  Duplicate "__source" prop found:
  6  |  const container = document.getElementById('root');
  7  |  const root = createRoot(container!);
  8  |  root.render(<React.StrictMode __self={this} __source={{
     |                                              ^
  9  |    fileName: _jsxFileName,
  10 |    lineNumber: 11,

  Duplicate "__self" prop found:
  11 |    columnNumber: 5
  12 |  }}>
  13 |          <App __self={this} __source={{
     |               ^
  14 |      fileName: _jsxFileName,
  15 |      lineNumber: 12,

  Duplicate "__source" prop found:
  11 |    columnNumber: 5
  12 |  }}>
  13 |          <App __self={this} __source={{
     |                             ^
  14 |      fileName: _jsxFileName,
  15 |      lineNumber: 12,`

**Comment by gregorip02** [comment]
> I don't think it's a wails bug, it happened to me with a Laravel, React and Vite application. I fixed it putting `jsxRuntime: classic` in react plugin at `vite.config.js`
> 
> ```js
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react'
> 
> export default defineConfig({
>   plugins: [
>     /* More plugin settings */
>     react({
>       jsxRuntime: 'classic'
>     })
>   ]
> })
> ```

This change doesn't works actually 🙅🏾‍♂️.

**Comment by learncodingforweb** [comment]
Check repository link having error even after modification
[https://github.com/learncodingforweb/desktop_app.git](Repository link)

**Comment by LucasCNordstrom** [comment]
> I don't think it's a wails bug, it happened to me with a Laravel, React and Vite application. I fixed it putting `jsxRuntime: classic` in react plugin at `vite.config.js`
> 
> ```js
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react'
> 
> export default defineConfig({
>   plugins: [
>     /* More plugin settings */
>     react({
>       jsxRuntime: 'classic'
>     })
>   ]
> })
> ```

This was perfect, worked fine!

**Comment by leaanthony** [comment]
Closing this as it's not a Wails bug

**Comment by lxcool9243** [comment]
> I don't think it's a wails bug, it happened to me with a Laravel, React and Vite application. I fixed it putting `jsxRuntime: classic` in react plugin at `vite.config.js`
> 
> ```js
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react'
> 
> export default defineConfig({
>   plugins: [
>     /* More plugin settings */
>     react({
>       jsxRuntime: 'classic'
>     })
>   ]
> })
> ```

It worked for me and saved the day
