### ISSUE TITLE
Build failed in windows amd64

### ISSUE THREAD

**Issue by beproactivegr** [wailsapp/wails#2653]
### Description

I am running wails build or wails dev and I am receiving the following error:

`DEB | Using go webview2loader
Wails CLI v2.4.1

Executing: go mod tidy
  • Generating bindings: 
  ERROR  
          fork/exec C:\Users\USER~1\AppData\Local\Temp\wailsbindings.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

### To Reproduce

1. Run wails dev in Windows 11.

### Expected behaviour

Enable wails development mode.

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 113.0.1774.35
npm        | N/A          | Installed | 9.6.6
*upx       | N/A          | Installed | upx 4.0.2
*nsis      | N/A          | Installed | v3.08
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

**Comment by beproactivegr** [comment]
Fixed

**Comment by liaosiqian** [comment]
> Fixed

How did you fix it? I upgraded my Go version -> 1.21.1  and still encounter this problem.
