### ISSUE TITLE
Error detected in Webview2: The parameter is incorrect

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#3759]
### Description

I get this error when I try to run the application on _Windows 10 Version 1607 (OS Build 14393.2906)_
> Error detected in Webview2:
> The parameter is incorrect.
> [0920/021755.722:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412

This problem occurs when the project uses _github.com/wailsapp/go-webview v1.0.16_
If I change to _github.com/wailsapp/go-webview v1.0.10_ the application runs without errors

When I run the same application on my main OS Windows 10 (Build: 22000) there is no such error

### To Reproduce

1. Create project using any template
2. Build the application and run it

### Expected behaviour

Running the application should not cause an error on some versions of Windows 10

### System Details

```shell
# Wails
Version | v2.9.2

# System
| OS           | Windows 10 Home
| Version      | 2009 (Build: 22000)
| ID           | 21H2
| Go Version   | go1.22.6

# Dependencies
| Dependency | Package Name | Status    | Version
| WebView2   | N/A          | Installed | 128.0.2739.79
| Nodejs     | N/A          | Installed | 20.13.1
| npm        | N/A          | Installed | 10.8.0
```

**Comment by cuijixiong1** [comment]
Have you solved it yet

**Comment by leaanthony** [comment]
As I won't be able to reproduce your setup, could you please do the following:
- Please follow this guide: https://wails.io/docs/guides/local-development
- Checkout the go-webview2 project from GitHub
- Use the `replace` directive in your application to use the checked out version of go-webview2
- Use `git bisect` to find the line that is throwing that error

I suspect it's a webview2 version mismatch (too old or bad guard)

**Comment by mycodebroken** [comment]
> As I won't be able to reproduce your setup, could you please do the following:
> 
> * Please follow this guide: https://wails.io/docs/guides/local-development
> * Checkout the go-webview2 project from GitHub
> * Use the `replace` directive in your application to use the checked out version of go-webview2
> * Use `git bisect` to find the commit that introduced the issue
> * If you have any ideas where the issue might be, some `printf` debugging would help determine the line.
> 
> I suspect it's a webview2 version mismatch (too old or bad guard)

I did everything as you recommended and still get this error using `go-webview2 v1.0.17`
It works only if you downgrade to `go-webview2 v1.0.10`

`Stack trace:`
```
goroutine 1 [running, locked to thread]:
github.com/wailsapp/go-webview2/pkg/edge.globalErrorHandler({0x1533ae0, 0x185daf8})
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:29 +0x6e
github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).errorCallback(0xc0001c0240, {0x1533ae0, 0x185daf8})
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:123 +0x31
github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).EnvironmentCompleted(0xc0001c0240, 0x0, 0x40f8000cc010)
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:307 +0x46e
github.com/wailsapp/go-webview2/pkg/edge.(*environmentCreatedHandler).EnvironmentCompleted(0xc0001881a8, 0x0, 0x40f8000cc010)
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/create_env_go.go:27 +0x54
github.com/wailsapp/go-webview2/webviewloader.(*environmentCreatedHandler).EnvironmentCompleted(0xc0001867a0, 0x0, 0x40f8000cc010)
        C:/Users/Administrator/Documents/go-webview2/webviewloader/env_create.go:156 +0x122
github.com/wailsapp/go-webview2
```

`git bisect:`
```
d039be2685870668a5a7d29f6ba3feb201dbcdd6 is the first bad commit
commit d039be2685870668a5a7d29f6ba3feb201dbcdd6 (HEAD, tag: v1.0.11)
Author: Lea Anthony <lea.anthony@gmail.com>
Date:   Sun Jul 28 11:38:04 2024 +1000

    Better error handling

 pkg/edge/chromium.go          | 185 +++++++++++++++++++++++++++++++-----------
 pkg/edge/chromium_386.go      |   5 +-
 pkg/edge/chromium_amd64.go    |   7 +-
 pkg/edge/chromium_arm64.go    |   5 +-
 pkg/edge/create_env_native.go |   5 +-
 5 files changed, 156 insertions(+), 51 deletions(-)
 ```

- OS: **_Windows Server 2016 Standard_**
- Version: **_1607 (Build: 14393)_**
- Go Version: **_go1.23.3_**
- Platform: **_windows_**
- Architecture: **_amd64_**
- WebView2 **_131.0.2903.51_**
- Nodejs **_22.11.0_**
- npm **_10.9.0_**

**Comment by mycodebroken** [comment]
```
Error detected in Webview2:
 The parameter is incorrect.

Stack:
1. github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).errorCallback
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:135
2. github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).EnvironmentCompleted
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:319
3. github.com/wailsapp/go-webview2/pkg/edge.(*environmentCreatedHandler).EnvironmentCompleted
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/create_env_go.go:27
4. github.com/wailsapp/go-webview2/webviewloader.(*environmentCreatedHandler).EnvironmentCompleted
        C:/Users/Administrator/Documents/go-webview2/webviewloader/env_create.go:156
5. github.com/wailsapp/go-webview2/webviewloader._iCoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerInvoke
        C:/Users/Administrator/Documents/go-webview2/webviewloader/env_create_completed.go:40
6. runtime.callbackWrap
        C:/Program Files/Go/src/runtime/syscall_windows.go:396
7. runtime.cgocallbackg1
        C:/Program Files/Go/src/runtime/cgocall.go:442
8. runtime.cgocallbackg
        C:/Program Files/Go/src/runtime/cgocall.go:361
9. runtime.cgocallback
        C:/Program Files/Go/src/runtime/asm_amd64.s:1084
10. runtime.systemstack_switch
        C:/Program Files/Go/src/runtime/asm_amd64.s:479
11. runtime.cgocall
        C:/Program Files/Go/src/runtime/cgocall.go:185
12. runtime.syscall_syscalln
        C:/Program Files/Go/src/runtime/syscall_windows.go:521
13. syscall.Syscall6
        C:/Program Files/Go/src/runtime/syscall_windows.go:463
14. golang.org/x/sys/windows.(*Proc).Call
        C:/Users/Administrator/go/pkg/mod/golang.org/x/sys@v0.27.0/windows/dll_windows.go:178
15. github.com/wailsapp/go-webview2/webviewloader.createWebViewEnvironmentWithClientDll
        C:/Users/Administrator/Documents/go-webview2/webviewloader/env_create.go:112
16. github.com/wailsapp/go-webview2/webviewloader.CreateCoreWebView2EnvironmentWithOptions
        C:/Users/Administrator/Documents/go-webview2/webviewloader/env_create.go:61
17. github.com/wailsapp/go-webview2/pkg/edge.createCoreWebView2EnvironmentWithOptions
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/create_env_go.go:13
18. github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).Embed
        C:/Users/Administrator/Documents/go-webview2/pkg/edge/chromium.go:169
19. github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).setupChromium
        C:/Users/Administrator/Documents/wails/v2/internal/frontend/desktop/windows/frontend.go:523
20. github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run
        C:/Users/Administrator/Documents/wails/v2/internal/frontend/desktop/windows/frontend.go:163
21. github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run
        C:/Users/Administrator/Documents/wails/v2/internal/frontend/devserver/devserver.go:128
22. github.com/wailsapp/wails/v2/internal/app.(*App).Run
        C:/Users/Administrator/Documents/wails/v2/internal/app/app_dev.go:32
23. github.com/wailsapp/wails/v2/pkg/application.(*Application).Run
        C:/Users/Administrator/Documents/wails/v2/pkg/application/application.go:73
24. github.com/wailsapp/wails/v2.Run
        C:/Users/Administrator/Documents/wails/v2/wails.go:14
25. main.main
        C:/Users/Administrator/Documents/myproject/main.go:19
26. runtime.main
        C:/Program Files/Go/src/runtime/proc.go:272
[1126/041923.448:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

**Comment by leaanthony** [comment]
Can you both please paste the full `wails doctor` output (feel free to remove anything you don't want to share) because there are some things we need to see there

**Comment by Snshadow** [comment]
This is the issue which I encountered too, looks like it happen in the Windows 10 versions prior to 1803 when using the webview2 version later then 118(maybe related with this [issue](https://github.com/wailsapp/go-webview2/issues/24))?.

Looking at the goroutine dump, the `The parameter is incorrect.` occurs when calling
```
_, _, err = env.vtbl.CreateCoreWebView2Controller.Call(
		uintptr(unsafe.Pointer(env)),
		e.hwnd,
		uintptr(unsafe.Pointer(e.controllerCompleted)),
	)
```
from
```
github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).EnvironmentCompleted(chromium.go:298)
github.com/wailsapp/go-webview2/pkg/edge.(*environmentCreatedHandler).EnvironmentCompleted(create_env_go.go:27)
github.com/wailsapp/go-webview2/webviewloader.(*environmentCreatedHandler).EnvironmentCompleted(env_create.go:156)
github.com/wailsapp/go-webview2/webviewloader._iCoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerInvoke(env_create_completed.go:40)
runtime.call32(asm_amd64.s:776)
runtime.callbackWrap(syscall_windows.go:396)
runtime.cgocallbackg1(cgocall.go:442)
runtime.cgocallbackg(cgocall.go:361)
runtime.cgocallbackg(<autogenerated>:1)
runtime.cgocallback(asm_amd64.s:1084)
runtime.callbackasm1(sys_windows_amd64.s:232)
```
this call stack. The `env.vtbl.CreateCoreWebView2Controller.Call` returns `windows.ERROR_INVALID_PARAMETER` so the application fails create a new webview.

The interesting thing is that from Windows 10 1507 the error occurs at the same function but the error code is `windows.ERROR_PROC_NOT_FOUND`.

**Comment by Snshadow** [comment]
The outputs of the `wails doctor` look like this.
Windows 10 1607(This one has `ERROR_INVALID_PARAMETER`)
```
# Wails
Version | v2.9.2

# System
┌──────────────────────────────────────────────────────── ─────────┐
| OS           | Windows 10 Pro                                   |
| Version      | 1607 (Build: 14393)                              |
| ID           |                                                  |
| Go Version   | go1.23.3                                         |
| Platform     | windows                                          |
| Architecture | amd64                                            |
└──────────────────────────────────────────────────────── ─────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 131.0.2903.70 |
| Nodejs     | N/A          | Available |               |
| npm        | N/A          | Available |               |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘
```

Windows 10 1507(This one has `ERROR_PROC_NOT_FOUND`)
```
# Wails
Version | v2.9.2

# System
┌─────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                   |
| Version      |  (Build: 10240)                                  |
| ID           |                                                  |
| Go Version   | go1.23.3                                         |
| Platform     | windows                                          |
| Architecture | amd64                                            |
└─────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 131.0.2903.70 |
| Nodejs     | N/A          | Available |               |
| npm        | N/A          | Available |               |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘
```

**Comment by mycodebroken** [comment]
> Can you both please paste the full `wails doctor` output (feel free to remove anything you don't want to share) because there are some things we need to see there

# Wails
Version `v2.9.2`
Revision `ba38474050da9381c9a1bd8a6c9a2e8b5f27a038`
Modified `false`

# System
OS `Windows Server 2016 Standard`
Version `1607 (Build: 14393)`
Go Version `go1.23.3`
Platform `windows`
Architecture `amd64`

# Dependencies
WebView2 `131.0.2903.63`
Nodejs `22.11.0`
npm `10.9.0`

**Comment by Snshadow** [comment]
> This problem occurs when the project uses _github.com/wailsapp/go-webview v1.0.16_ If I change to _github.com/wailsapp/go-webview v1.0.10_ the application runs without errors

I have checked that using go-webview2@v1.0.10 work for both 64 bit and 32 bit for Windows 10 prior to 1803 using the latest webview2 runtime(131.0.2903.70).

**Comment by Snshadow** [comment]
> Looking at the goroutine dump, the `The parameter is incorrect.` occurs when calling
> 
> ```
> _, _, err = env.vtbl.CreateCoreWebView2Controller.Call(
> 		uintptr(unsafe.Pointer(env)),
> 		e.hwnd,
> 		uintptr(unsafe.Pointer(e.controllerCompleted)),
> 	)
> ```
> 
> from
> 
> ```
> github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).EnvironmentCompleted(chromium.go:298)
> github.com/wailsapp/go-webview2/pkg/edge.(*environmentCreatedHandler).EnvironmentCompleted(create_env_go.go:27)
> github.com/wailsapp/go-webview2/webviewloader.(*environmentCreatedHandler).EnvironmentCompleted(env_create.go:156)
> github.com/wailsapp/go-webview2/webviewloader._iCoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerInvoke(env_create_completed.go:40)
> runtime.call32(asm_amd64.s:776)
> runtime.callbackWrap(syscall_windows.go:396)
> runtime.cgocallbackg1(cgocall.go:442)
> runtime.cgocallbackg(cgocall.go:361)
> runtime.cgocallbackg(<autogenerated>:1)
> runtime.cgocallback(asm_amd64.s:1084)
> runtime.callbackasm1(sys_windows_amd64.s:232)
> ```
> 
> this call stack. The `env.vtbl.CreateCoreWebView2Controller.Call` returns `windows.ERROR_INVALID_PARAMETER` so the application fails [create a new webview](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.2903.40#createcorewebview2controller).

Looking at the part that calls the CreateCoreWebView2Controller function, actually this function fails in the v1.0.10 too,
- v1.0.10
https://github.com/wailsapp/go-webview2/blob/94c719c3fd031470e3c1b80cff0eadb71ffc3077/pkg/edge/chromium.go#L250-L263
- v1.0.11
https://github.com/wailsapp/go-webview2/blob/d039be2685870668a5a7d29f6ba3feb201dbcdd6/pkg/edge/chromium.go#L114-L117
https://github.com/wailsapp/go-webview2/blob/d039be2685870668a5a7d29f6ba3feb201dbcdd6/pkg/edge/chromium.go#L283-L302
the reason that application fails to run when using the version later then v1.0.10 is that os.Exit(1) is called when the function fails, should this be handled in go-webview2?

**Comment by leaanthony** [comment]
> Looking at the part that calls the CreateCoreWebView2Controller function, actually this function fails in v1.0.10 too,
Do you know why this is erroring? We were just ignoring them before so I get why it wasn't failing then, but if there's an error I'm surprised it works at all!

**Comment by Snshadow** [comment]
Using the [sample](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample) from WebView2Sample2 repository, the [call for CreateCoreWebView2Controller](https://github.com/MicrosoftEdge/WebView2Samples/blob/96ef509eb5f7e13e31a2e7b4c8d561310556490c/SampleApps/WebView2APISample/AppWindow.cpp#L1457-L1460) succeeds for Windows 11 23H2 and Windows 10 prior to 1803, there should be something different with the implementation in go-webview2 and the working case. We would have to figure not what is causing the function to fail.

**Comment by Snshadow** [comment]
Digging into the call of CreateCoreWebView2Controller with x64dbg the stack looks like this
```
,000000B71A3FEA78,00007FFCA356383C,00007FFCA34DA496,30,System,user32.ValidateDpiAwarenessContext+22
,000000B71A3FEAA8,00007FFC80100B0F,00007FFCA356383C,80,User,user32.AreDpiAwarenessContextsEqual+1C
,000000B71A3FEB28,00007FFC80124C66,00007FFC80100B0F,2E0,User,"embeddedbrowserwebview.public: long __cdecl embedded_browser_webview_current::Controller::Initialize(struct HWND__*, struct IUnknown *, class embedded_browser::mojom::EmbeddedBrowser *)+27D"
,000000B71A3FEE08,00007FFC80117134,00007FFC80124C66,1D0,User,"embeddedbrowserwebview.public: long __cdecl embedded_browser_webview_current::EmbeddedBrowserWebView::RuntimeClassInitialize(class std::__Cr::unique_ptr<struct embedded_browser_webview_current::WebViewCreationParams, struct std::__Cr::default_delete<struct embedded_browser_webv"
,000000B71A3FEFD8,00007FFC8011A396,00007FFC80117134,F0,User,embeddedbrowserwebview.embedded_browser_webview_current::internal::EBWebViewEnvironment::CreateWebViewGeneric+5AC
,000000B71A3FF0C8,0000000000B00189,00007FFC8011A396,170,User,"embeddedbrowserwebview.public: virtual long __cdecl embedded_browser_webview_current::internal::EBWebViewEnvironment::CreateCoreWebView2ControllerWithOptions(struct HWND__*, struct ICoreWebView2ControllerOptions *, struct ICoreWebView2CreateCoreWebView2ControllerCompletedHandle"
,000000B71A3FF238,0000000000AFE50D,0000000000B00189,30,User,go-gui.0000000000B00189
,000000B71A3FF268,0000000000AFE583,0000000000AFE50D,8E5DA8408,User,go-gui.0000000000AFE50D
,000000C0001A7670,0000000000AF0332,0000000000AFE583,68,User,go-gui.0000000000AFE583
,000000C0001A76D8,0000000000ADF1C9,0000000000AF0332,28,User,go-gui.0000000000AF0332
,000000C0001A7700,0000000000AFA609,0000000000ADF1C9,50,User,go-gui.0000000000ADF1C9
,000000C0001A7750,0000000001047815,0000000000AFA609,6B8,User,go-gui.0000000000AFA609
,000000C0001A7E08,0000000001042C76,0000000001047815,1E8,User,go-gui.0000000001047815
,000000C0001A7FF0,000000000104BD54,0000000001042C76,40,User,go-gui.0000000001042C76
,000000C0001A8030,0000000000FA60E2,000000000104BD54,68,User,go-gui.000000000104BD54
,000000C0001A8098,0000000000FA62F7,0000000000FA60E2,48,User,go-gui.0000000000FA60E2
,000000C0001A80E0,0000000000AFCEC8,0000000000FA62F7,30,User,go-gui.0000000000FA62F7
,000000C0001A8110,0000000000ADF0A6,0000000000AFCEC8,3F0,User,go-gui.0000000000AFCEC8
,000000C0001A8500,0000000000A8A274,0000000000ADF0A6,B8,User,go-gui.0000000000ADF0A6
,000000C0001A85B8,0000000000A89F87,0000000000A8A274,80,User,go-gui.0000000000A8A274
,000000C0001A8638,0000000000B046EE,0000000000A89F87,28,User,go-gui.0000000000A89F87
,000000C0001A8660,0000000000AFE6CC,0000000000B046EE,FFFFFFF71A256C40,User,go-gui.0000000000B046EE
,000000B71A3FF2A0,0000000000B00495,0000000000AFE6CC,8,User,go-gui.0000000000AFE6CC
,000000B71A3FF2A8,0000000000ADEE3F,0000000000B00495,8,User,go-gui.0000000000B00495
,000000B71A3FF2B0,000000B71A3FF2C0,0000000000ADEE3F,8,User,go-gui.0000000000ADEE3F
,000000B71A3FF2B8,0000000000000000,000000B71A3FF2C0,,User,000000B71A3FF2C0
```

The function is called from embeddedbroswerwebview.dll, calling the CreateCoreWebView2ControllerWithOptions function, which internally calls user32.AreDpiAwarenessContextsEqual, this is where the last status is set to `ERROR_INVALID_PARAMETER`  and continue running the function procedure, but make the function return an error. Additionally, [AreDpiAwarenessContextsEqual](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-aredpiawarenesscontextsequal) was introduced in Windows 10 1607, which explains why the function returns `ERROR_PROC_NOT_FOUND` in Windows 10 1507.

Although it looks like this does not result in the failure of running the WebView2 process, the DPI setting may go weird without properly setting DPI awareness.

Comparing the api call from the WebView2 Sample and the wails application, looks like this functions fails in both of them, but from the WebView2 sample it does not return an error. I would have to investigate further.

**Comment by leaanthony** [comment]
We could guard that call behind a capabilities flag, rather than erroring.

**Comment by Snshadow** [comment]
Oops.. actually the `CreateCoreWebView2Controller` function runs successfully. Just realized that 
```go
_, _, err = env.vtbl.CreateCoreWebView2Controller.Call(
	uintptr(unsafe.Pointer(env)),
	e.hwnd,
	uintptr(unsafe.Pointer(e.controllerCompleted)),
)
```
is not a right way to handle an error as it returns HRESULT value to indicate an error.
> public HRESULT [CreateCoreWebView2Controller](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.2903.40#createcorewebview2controller)(HWND parentWindow, ICoreWebView2CreateCoreWebView2ControllerCompletedHandler * handler)

According to [syscall.Proc.Call](https://pkg.go.dev/syscall?GOOS=windows#Proc.Call) which is used in ComProc.Call when calling the function, the err value is supposed to be a non-nil error(as written in the document).
A correct way to handle an error is using should be like
```go
hres, _, _ := env.vtbl.CreateCoreWebView2Controller.Call(
	uintptr(unsafe.Pointer(env)),
	e.hwnd,
	uintptr(unsafe.Pointer(e.controllerCompleted)),
)
if int32(hres) < 0 { // HRESULT(int32) smaller then 0 means it failed(https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-failed)
	// https://learn.microsoft.com/en-us/windows/win32/seccrypto/common-hresult-values
	// do error handling with the HRESULT value 
}
```

Looks like most of the calls are handled in an inappropriate way..

Creating a wrapper(maybe something like [this](https://github.com/go-ole/go-ole/blob/6c7f9027aa642e576d44a9f87344e11d1413ac68/utility.go#L95-L101)) to handle HRESULT would be nice.

**Comment by stffabi** [comment]
Yeah handling COM call errors in a wrong way is a common issue. Most calls are currently handled in a wrong way.

**Comment by Snshadow** [comment]
@leaanthony I have made a pull request at https://github.com/wailsapp/go-webview2/pull/25 to fix the com error handling issue. Could you check if it's good to go?

**Comment by james-vanrossum-sonardyne** [comment]
How's this looking? I seem to have the same problem on another Windows 10 PC running version:
Win 10 Enterprise 2016 LTSB - V10.0.14393
Running a built application compiled by another PC won't work, and also wails dev doesn't work on my machine with a similar error:
``` 
INF | Serving assets from frontend DevServer URL: http://localhost:5173/
DEB | WebView2 Runtime Version '131.0.2903.99' installed. Minimum version required: 94.0.992.31.
DEB | [DevWebServer] Serving DevServer at http://localhost:34115
Error detected in Webview2:
 The parameter is incorrect.
[1216/131148.934:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

**Comment by leaanthony** [comment]
The fix was committed 🤷 This issue should be closed. I'd suggest you open another issue and fill in the issue template 🙏

**Comment by Snshadow** [comment]
@Pejaiii If the problem is coming from this issue, running these command should make it work.
```
go mod edit --replace github.com/wailsapp/go-webview2=github.com/wailsapp/go-webview2@v1.0.19-0.20241205184759-04d9b746201a
go mod tidy
```
The commit did not make it to the released version, and it need some considerations according to https://github.com/wailsapp/wails/issues/3931#issuecomment-2519498697.

**Comment by W1M0R** [comment]
I still get this issue, even if I use wailsapp/go-webview2 v1.0.21.

```
[WebView2 Error] The parameter is incorrect.

Stack trace:
2025/06/17 15:54:58 1: github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).errorCallback
        C:/Users/user2/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.21/pkg/edge/chromium.go:151        
2025/06/17 15:54:58 2: github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).Focus
        C:/Users/user2/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.21/pkg/edge/chromium.go:575        
2025/06/17 15:54:58 3: tms/pkg/edge/webview.(*WebviewApp).StartWait.func1
        C:/Users/user2/sdl/src/tms/tms/pkg/edge/webview/webview.go:166
2025/06/17 15:54:58 4: runtime.callbackWrap
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/syscall_windows.go:396
2025/06/17 15:54:58 5: runtime.cgocallbackg1
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/cgocall.go:446
2025/06/17 15:54:58 6: runtime.cgocallbackg
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/cgocall.go:350
2025/06/17 15:54:58 7: runtime.cgocallback
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/asm_amd64.s:1084
2025/06/17 15:54:58 8: runtime.systemstack_switch    
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/asm_amd64.s:479
2025/06/17 15:54:58 9: runtime.cgocall
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/cgocall.go:185
2025/06/17 15:54:58 10: runtime.syscall_syscalln     
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/syscall_windows.go:521
2025/06/17 15:54:58 11: syscall.SyscallN
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/runtime/syscall_windows.go:500
2025/06/17 15:54:58 12: syscall.(*Proc).Call
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/syscall/dll_windows.go:167
2025/06/17 15:54:58 13: syscall.(*LazyProc).Call     
        C:/Users/user2/AppData/Roaming/mise/installs/go/1.24.4/src/syscall/dll_windows.go:287
2025/06/17 15:54:58 14: github.com/gonutz/w32/v2.GetMessage
        C:/Users/user2/go/pkg/mod/github.com/gonutz/w32/v2@v2.11.1/functions.g       
```

**Comment by leaanthony** [comment]
Windows 10 Build 14393 (Anniversary Update, July 2016) predates WebView2 — WebView2 requires Windows 10 version 1909 (Build 18363) or later as its minimum supported version. There's nothing Wails can do to support a platform that the underlying WebView2 runtime itself doesn't run on.

The minimum supported Windows version for Wails (both v2 and v3) is Windows 10 1909+. Closing as unsupported platform — thanks!
