### ISSUE TITLE
[v3]Mac OS Monterey (12.6+) unable to type in input

### ISSUE THREAD

**Issue by Kalcode** [wailsapp/wails#4061]
### Description

When installing wails3 on Mac OS 12.7 & 12.6, when running `wails3 dev` the window will appear, the keyboard events appear be be ignore when typing in the input box. Enter seems to be received.

Following further testing, I followed the same process on 14+ Mac OS M3, and was able to use the keyboard as expected.

No errors were observed in console on inspecting the element in the VM.

**For reference:** 

Discussion took place in the Discord, and a thread was created https://discord.com/channels/1042734330029547630/1338598092852695184

### To Reproduce

The issue was recreated by installing a fresh VM using Mac OS 12.6 (the free download inside the parallels software), did the following

1. Install Parallels Desktop and use free trial
3. Installed MacOS 12.6 running in Parallels Desktop
4. Installed Xcode
5. Installed brew
6. Installed go via brew
7. Installed nvm
8. Installed node 21 via nvm
9. Installed wails3 (created two projects with and without a template)10. `wails3 init -n test` & `wails3 dev`
11. `wails3 init -n test -t react-ts` & `wails3 dev`

### Expected behaviour

Can type into input box and be greeted with the "name" that the user inputted

### Screenshots

![Image](https://github.com/user-attachments/assets/b43a8566-27d9-44ff-9345-6e963cdfe347)

### Attempted Fixes

Removed the for loop for the time event, removed the use effects and any imports on the frontend (reduced to just a `<form><input>`).

### System Details

```shell
# System

┌────────────────────────────────────────────────────────────────────────────┐
| Name          | MacOS                                                      |
| Version       | 12.7                                                       |
| ID            | 21G816                                                     |
| Branding      | Monterey                                                   |
| Platform      | darwin                                                     |
| Architecture  | arm64                                                      |
| Apple Silicon | true                                                       |
| CPU           | Apple M1 Max                                               |
| CPU 1         | Apple M1 Max                                               |
| CPU 2         | Apple M1 Max                                               |
| GPU           | 32 cores, Metal Family: Supported, Metal GPUFamily Apple 7 |
| Memory        | 32 GB                                                      |
└────────────────────────────────────────────────────────────────────────────┘

# Build Environment

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.9                                                                                                            |
| Go Version     | go1.23.5                                                                                                                  |
| -buildmode     | exe                                                                                                                       |
| -compiler      | gc                                                                                                                        |
| CGO_CFLAGS     |                                                                                                                           |
| CGO_CPPFLAGS   |                                                                                                                           |
| CGO_CXXFLAGS   |                                                                                                                           |
| CGO_ENABLED    | 1                                                                                                                         |
| CGO_LDFLAGS    |                                                                                                                           |
| DefaultGODEBUG | asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1 |
| GOARCH         | arm64                                                                                                                     |
| GOARM64        | v8.0                                                                                                                      |
| GOOS           | darwin                                                                                                                    |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies

┌───────────────────────────┐
| Xcode cli tools | 2395    |
| npm             | 10.5.0  |
| *NSIS           | v3.10   |
└─ * - Optional Dependency ─┘

# Diagnosis

 SUCCESS  Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
I think this CSS issue is now fixed?

**Comment by fbbdev** [comment]
@leaanthony Debugged but not fixed yet AFAIK.

Requires an edit to every template stylesheet.

I checked again the specs for user-select and it should be enough to move the property from the [* selector](https://github.com/wailsapp/wails/blob/96fa0d25f0f6ef2678c644a744d326222b84e383/v3/internal/templates/vanilla/frontend/public/style.css#L18) to the [:root selector](https://github.com/wailsapp/wails/blob/96fa0d25f0f6ef2678c644a744d326222b84e383/v3/internal/templates/vanilla/frontend/public/style.css#L1) above (already tested and it works).

**Comment by leaanthony** [comment]
@Kalcode - Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/local-development#testing-a-pr). Let us know how you get on 👍

**Comment by leaanthony** [comment]
This PR has now been approved. Let me know how you get on 👍
