### ISSUE TITLE
1.5.0 serve not working

### ISSUE THREAD

**Issue by dedo1911** [wailsapp/wails#408]
**Description**
I'm having issues with serve command. It's just trying to launch last built executable instead.

```
wails serve
Wails v1.5.0 - Serving Application

> Ensuring Dependencies are up to date...
> Packing + Compiling project...
Awesome! Project 'My Project' built!
Serving Application: S:\Gitea\wailstest\my-project\build\my-project
Error: exec: "S:\\Gitea\\wailstest\\my-project\\build\\my-project": file does not exist
```

**To Reproduce**
Steps to reproduce the behaviour:
1. wails init (and select anything, it doesn't matter)
2. wails serve

**Expected behaviour**
Wait for the frontend to connects.
1.0.3-pre2 was working fine.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.5.0 |
| Go Version    | go1.14.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 8.1.0 |
| Npm           | 6.13.7 |
| Node          | v13.8.0|

**Comment by minaandrawos** [comment]
Having same issue

**Comment by leaanthony** [comment]
Thanks for the report. @minaandrawos Windows too?

**Comment by minaandrawos** [comment]
Yes

**Comment by masterdubs** [comment]
Looks like the cross-platform build is broken at the same time.

**Comment by leaanthony** [comment]
@masterdubs - in what way? I tried it yesterday and it was fine: https://github.com/wailsapp/wails/issues/412

**Comment by leaanthony** [comment]
@dedo1911 - does the built binary exist anywhere? Like project root?

**Comment by leaanthony** [comment]
@masterdubs - in what way? I tried it yesterday and it was fine.

**Comment by dedo1911** [comment]
@leaanthony  just tried with 1.6.0-pre2 and the executable exists in build directory (there's no extension).
Launching that executable manually it looks like that's the correct "serve" executable.

**Comment by leaanthony** [comment]
So it looks like `.exe` isn't being added to the target binary?

**Comment by masterdubs** [comment]
simply, as usual, building works, but in the end I don't get any bin (on mac for windows ). I will try the latest pre looks like 1.6 is out.

**Comment by dedo1911** [comment]
> 
> 
> So it looks like `.exe` isn't being added to the target binary?

Yes. that's the issue I think.

I tried to:
- `wails serve` (it creates a file without extension)
- rename "build/myapp" to "build/myapp.exe"
- run `wails serve` again

and it creates "myapp" again but runs "myapp.exe" correctly.
I think adding .exe to the final binary should solve the issue.

**Comment by leaanthony** [comment]
Perfect. This must be a regression with the recent build changes.

**Comment by masterdubs** [comment]
Fixed in latest pre.

**Comment by dedo1911** [comment]
> 
> 
> Fixed in latest pre.

Are you on Windows too? 1.6.0-pre2 is still broken on Windows

**Comment by alienatorZ** [comment]
When I use Windows with version 1.5.0 using wails serve it creates an app in the build directory without .exe. I just rename the build file to add the .exe and re-run wails serve and it works.

**Comment by leaanthony** [comment]
Merged PR - Please let me know if this fixes it.

**Comment by dedo1911** [comment]
v1.6.0-pre3 is working properly now (Windows)

**Comment by zhuqiyun** [comment]
> Merged PR - Please let me know if this fixes it.
v1.6.0-pre5 ，can not  wails  serve too  ，windows10

**Comment by dedo1911** [comment]
@zhuqiyun can you please provide the console output of the wails serve command?
