### ISSUE TITLE
Expose `Once` to Go runtime

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#599]
From @GeekStocks:

I have a need to respond to an event one (and **only** one) time. In other frameworks I am used to seeing `.On` and `.Off` logic so that a listener can be removed after the first run (in my use case). I was surprised to see there is no `.Off` in Wails and I was going to propose a pull request to add it. _That is, until I read the rather fancy expiration logic already written in_ `Manager.Start()`:

```
// Update listen counter
if listener.counter > 0 {
	listener.counter = listener.counter - 1
	if listener.counter == 0 {
		listener.expired = true
	}
}
```

So since you've already implemented a way to expire a listener after x runs, why does `.On` not expose it here, but rather just hard codes a zero?

```
// at lib/event/manager.go

// On adds a listener for the given event
func (e *Manager) On(eventName string, callback func(...interface{})) {
	// Add a persistent eventListener (counter = 0)
	e.addEventListener(eventName, callback, 0)
}
```

Have I missed the proper way to `.On` an event x number of times? **Thanks!**

_Originally posted by @GeekStocks in https://github.com/wailsapp/wails/discussions/598_

**Comment by leaanthony** [comment]
Fixed in latest pre-release

**Comment by GeekStocks** [comment]
Sorry to be the bearer of bad news, but no, its not fixed. See [my test on the discussion thread](https://github.com/wailsapp/wails/discussions/598#discussioncomment-337858)

I'll look to see if I can find the issue with it not expiring as expected.

**Comment by GeekStocks** [comment]
Ug, this is a killer. So, I changed my code to:

`runtime.Events.OnMultiple("reactAppLoaded_", s.handleReactAppLoaded, 1)`

and sadly the event also **never expires** when loaded this way either. Something deep going on here....

**Comment by leaanthony** [comment]
It could have been the switch to uint. I'll check today if i get the time.

**Comment by GeekStocks** [comment]
> Also, if it's that mission critical to you, i'd suggest having a flag to indicate if it's been called or not as a workaround.

I had actually done that workaround already just as "defensive code" 🤣 but **NO** I'm not mission critical here. Currently this is exploratory and if Wails works out I'll be running projects through it.
