### ISSUE TITLE
Unable to kill child process started by exec.Command

### ISSUE THREAD

**Issue by OneSeven** [wailsapp/wails#932]
**Description**
Unable to kill child process started by exec.Command

**To Reproduce**
Steps to reproduce the behaviour:
In Startup or elsewhere
```go
var cmd *exec.Cmd

func (b *App) startup(ctx context.Context) {
	// Perform your setup here
	b.ctx = ctx
	go func() {
		cmd = exec.Command("./livego")
                cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
		_ = cmd.Start()
		_ = cmd.Wait()
	}()
}

func (b *App) shutdown(ctx context.Context) {
	// Perform your teardown here
	_ = cmd.Process.Kill()
}
``` 
Debugging through wails dev can be killed
The program after wails build cannot be killed

**Expected behaviour**
End the subroutine before closing the program

**Screenshots**

After starting the program :

![yyyyyyyy](https://user-images.githubusercontent.com/17974392/141076088-afca94e0-2230-4029-b134-4d9a82ec6668.png)

After closing the program window ：

![zzzzzzzz](https://user-images.githubusercontent.com/17974392/141076192-ea10cbad-d4f3-4f21-9179-d7c3e6723050.png)

**System Details**
windows10 21H1
wails v2.0.0-beta.20

**Additional context**

- ☑️ This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Nice catch! Confirmed and fixed in `master`. Will do a release tonight/tomorrow.

**Comment by marcio199226** [comment]
As a workaround I think invoking exec.CommandContext with context will destroy exec process once the app has been quit, at least that's what I'm doing in my app when I need that subprocess needs to be killed once app quits.
You should create a wide app context in main.go and pass it down to your "services" and you should listen for various signal 
i.e
`
os.Interrupt,
os.Kill,
syscall.SIGHUP,
syscall.SIGINT,
syscall.SIGTERM,
syscall.SIGQUIT,
`
Once that one of this will be triggered you have to cancel your ctx and your subprocess will be "killed" too, doing it this way even if your app crash or will be killed manually from system process manager your subprocesses will exit too

**Comment by OneSeven** [comment]
> As a workaround I think invoking exec.CommandContext with context will destroy exec process once the app has been quit, at least that's what I'm doing in my app when I need that subprocess needs to be killed once app quits. You should create a wide app context in main.go and pass it down to your "services" and you should listen for various signal i.e `os.Interrupt, os.Kill, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT,` Once that one of this will be triggered you have to cancel your ctx and your subprocess will be "killed" too, doing it this way even if your app crash or will be killed manually from system process manager your subprocesses will exit too

I tried to use exec.CommandContext and listen to the exit signal, but it still doesn’t work. Can you give your code and refer to it

**Comment by OneSeven** [comment]
@leaanthony In Shutdown, it is not only impossible to end the child process, but also to delete a local file. In wails dev, the normal wails build does not work. There may be other familiar behaviors.

**Comment by leaanthony** [comment]
The change on master will call the shutdown callback on the main thread synchronously. If this is not getting called. then let's open up a different ticket. From my perspective, I'm not sure what more we can do? Remember, when testing master, you need to use `replace` in your project's `go.mod`

**Comment by OneSeven** [comment]
> The change on master will call the shutdown callback on the main thread synchronously. If this is not getting called. then let's open up a different ticket. From my perspective, I'm not sure what more we can do? Remember, when testing master, you need to use `replace` in your project's `go.mod`

I tested the master and it is currently working fine

**Comment by leaanthony** [comment]
@OneSeven - are you saying shutdown isn't getting called when closing the program?
